name: threshold
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.1.5
  universal_html: ^1.2.3
  url_launcher_web: ^0.1.1+6
  url_launcher: ^5.4.11
  dwds: ^5.0.0
  modal_bottom_sheet: ^0.2.0+1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800

  assets: 
    - assets/images/Threshold.png
    - assets/images/bg-threshold.png
    - assets/images/Education.png
    - assets/images/Skills.png
    - assets/images/Intro.png
    - assets/icons/icons8-github-30.png
    - assets/icons/icons8-instagram-30.png
    - assets/icons/icons8-linkedin-2-30.png
    - assets/images/workbg/Threshold.png
    - assets/images/workbg/Arena.png
    - assets/images/workbg/Hustle.png
    - assets/images/workbg/Pointify.png
    - assets/images/workbg/Ujjay.png
    - assets/images/workbg/ujjay/
    - assets/images/workbg/pointify/
    - assets/images/workbg/hustle/
    - assets/images/workbg/arena/
    - assets/images/workbg/threshold/
